# Generated by Django 5.2.7 on 2025-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0002_alter_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(default='Описание'),
        ),
    ]
