# Generated by Django 5.2.8 on 2025-11-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0003_food_photo_alter_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(default='Описание', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='photos/default.jpg', upload_to='photos/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foods.food')),
            ],
        ),
    ]
